import os
from pathlib import Path
from datetime import datetime

def create_dashboard():
    """
    Creates a comprehensive dashboard using the visualizations generated by the analysis modules.
    Uses snake_case for function names as per user preferences.
    """
    print("Creating comprehensive dashboard...")
    
    outputDir = Path('output')
    if not outputDir.exists():
        print("Creating output directory...")
        outputDir.mkdir(exist_ok=True)
    
    # Create dashboard directory
    dashboardDir = Path('output/dashboard')
    dashboardDir.mkdir(exist_ok=True, parents=True)
    
    # Key visualizations to include in the dashboard
    keyVisualizations = [
        {'file': 'financial_impact_by_industry.png', 'title': 'Financial Impact by Industry'},
        {'file': 'attack_type_distribution.png', 'title': 'Attack Type Distribution'},
        {'file': 'vulnerability_distribution.png', 'title': 'Security Vulnerability Distribution'},
        {'file': 'resolution_time_by_attack.png', 'title': 'Resolution Time by Attack Type'},
        {'file': 'attack_type_by_industry.png', 'title': 'Attack Types by Industry'},
        {'file': 'resolution_vs_financial_loss.png', 'title': 'Resolution Time vs Financial Loss'}
    ]
    
    # Create dashboard HTML
    with open(dashboardDir / 'cybersecurity_dashboard.html', 'w') as f:
        f.write("""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Cybersecurity Breach Analysis Dashboard</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 20px;
                    background-color: #f5f5f5;
                }
                .dashboard-container {
                    max-width: 1200px;
                    margin: 0 auto;
                }
                .header {
                    background-color: #1a237e;
                    color: white;
                    padding: 20px;
                    border-radius: 10px 10px 0 0;
                    margin-bottom: 20px;
                }
                .header h1 {
                    margin: 0;
                }
                .visualization-row {
                    display: flex;
                    flex-wrap: wrap;
                    justify-content: space-between;
                    margin-bottom: 20px;
                }
                .visualization-card {
                    background-color: white;
                    border-radius: 10px;
                    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                    margin-bottom: 20px;
                    width: 48%;
                    overflow: hidden;
                }
                .visualization-card h2 {
                    padding: 15px;
                    margin: 0;
                    background-color: #f0f0f0;
                    font-size: 18px;
                    color: #333;
                }
                .visualization-card img {
                    width: 100%;
                    max-height: 400px;
                    object-fit: contain;
                    padding: 10px;
                }
                .footer {
                    text-align: center;
                    margin-top: 30px;
                    padding-top: 15px;
                    border-top: 1px solid #ddd;
                    color: #666;
                }
                .summary {
                    background-color: white;
                    border-radius: 10px;
                    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                    padding: 20px;
                    margin-bottom: 20px;
                }
                .summary h2 {
                    color: #1a237e;
                    margin-top: 0;
                }
            </style>
        </head>
        <body>
            <div class="dashboard-container">
                <div class="header">
                    <h1>Cybersecurity Breach Analysis Dashboard</h1>
                    <p>Comprehensive analysis of global cybersecurity breaches (2015-2024)</p>
                </div>
                
                <div class="summary">
                    <h2>Key Insights</h2>
                    <ul>
                        <li>Financial impact varies significantly by industry, with the highest losses observed in Banking/Finance/FinTech sector</li>
                        <li>Phishing and ransomware remain the most prevalent attack types across all industries</li>
                        <li>There is a strong correlation between incident resolution time and financial loss</li>
                        <li>Social engineering and unpatched software are the leading vulnerability types</li>
                        <li>Advanced defense mechanisms like AI-based detection significantly reduce resolution times</li>
                    </ul>
                </div>
                
                <div class="visualization-row">
        """)
        
        # Add all available visualizations (not just the key ones)
        visualizationFiles = []
        for file in os.listdir('.'):
            if file.endswith('.png'):
                visualizationFiles.append({
                    'file': file,
                    'title': ' '.join(word.capitalize() for word in file.replace('.png', '').split('_'))
                })
        
        # If no visualizations found, use the key visualizations list (for when files are moved)
        if not visualizationFiles:
            visualizationFiles = keyVisualizations
        
        # Add visualizations to the dashboard
        for i, viz in enumerate(visualizationFiles):
            if i > 0 and i % 2 == 0:
                f.write('</div>\n<div class="visualization-row">\n')
            
            f.write(f"""
                    <div class="visualization-card">
                        <h2>{viz['title']}</h2>
                        <img src="../{viz['file']}" alt="{viz['title']}">
                    </div>
            """)
        
        # Close the visualization row and add footer
        f.write("""
                </div>
                
                <div class="footer">
                    <p>Generated on """ + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + """</p>
                    <p>For more detailed analysis, refer to the individual analysis reports</p>
                </div>
            </div>
        </body>
        </html>
        """)
    
    # Create an index.md file with links to all reports and visualizations
    with open(dashboardDir / 'index.md', 'w') as f:
        f.write("# Cybersecurity Breach Analysis - Complete Results\n\n")
        f.write(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        f.write("## Interactive Dashboard\n")
        f.write("- [View Interactive Dashboard](cybersecurity_dashboard.html)\n\n")
        
        # List all summary reports (md files)
        f.write("## Summary Reports\n")
        summaryFiles = [file for file in os.listdir('.') if file.endswith('_summary.md')]
        for summary in summaryFiles:
            title = ' '.join(word.capitalize() for word in summary.replace('_summary.md', '').split('_'))
            f.write(f"- [{title}](../{summary})\n")
        f.write("\n")
        
        # List all visualizations (png files)
        f.write("## All Visualizations\n\n")
        
        # Group visualizations by type
        financialViz = [file for file in os.listdir('.') if file.startswith('financial_') and file.endswith('.png')]
        attackViz = [file for file in os.listdir('.') if file.startswith('attack_') and file.endswith('.png')]
        resolutionViz = [file for file in os.listdir('.') if (file.startswith('resolution_') or file.startswith('vulnerability_')) and file.endswith('.png')]
        otherViz = [file for file in os.listdir('.') if file.endswith('.png') and file not in financialViz and file not in attackViz and file not in resolutionViz]
        
        # Financial visualizations
        if financialViz:
            f.write("### Financial Impact\n")
            for viz in financialViz:
                title = ' '.join(word.capitalize() for word in viz.replace('.png', '').split('_'))
                f.write(f"- [{title}](../{viz})\n")
            f.write("\n")
        
        # Attack visualizations
        if attackViz:
            f.write("### Attack Patterns\n")
            for viz in attackViz:
                title = ' '.join(word.capitalize() for word in viz.replace('.png', '').split('_'))
                f.write(f"- [{title}](../{viz})\n")
            f.write("\n")
        
        # Resolution visualizations
        if resolutionViz:
            f.write("### Resolution & Vulnerability\n")
            for viz in resolutionViz:
                title = ' '.join(word.capitalize() for word in viz.replace('.png', '').split('_'))
                f.write(f"- [{title}](../{viz})\n")
            f.write("\n")
        
        # Other visualizations
        if otherViz:
            f.write("### Other Visualizations\n")
            for viz in otherViz:
                title = ' '.join(word.capitalize() for word in viz.replace('.png', '').split('_'))
                f.write(f"- [{title}](../{viz})\n")
    
    print(f"Dashboard created successfully at {dashboardDir / 'cybersecurity_dashboard.html'}")
    print(f"Index created successfully at {dashboardDir / 'index.md'}")

if __name__ == "__main__":
    create_dashboard()
